# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Generator(object):
    def setupUi(self, Generator):
        Generator.setObjectName("Generator")
        Generator.resize(904, 637)
        Generator.setStyleSheet("background-color: #e9e4d7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Generator)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_browser = QtWidgets.QTextBrowser(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_browser.sizePolicy().hasHeightForWidth())
        self.text_browser.setSizePolicy(sizePolicy)
        self.text_browser.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(17)
        self.text_browser.setFont(font)
        self.text_browser.setStyleSheet("background-color: #ebaaa3;\n"
"border-radius: 5px;\n"
"padding-left: 10px;\n"
"padding-top: 10px;")
        self.text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_browser.setObjectName("text_browser")
        self.horizontalLayout.addWidget(self.text_browser)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selected_templates_label = QtWidgets.QLabel(Generator)
        self.selected_templates_label.setAlignment(QtCore.Qt.AlignCenter)
        self.selected_templates_label.setObjectName("selected_templates_label")
        self.verticalLayout_2.addWidget(self.selected_templates_label)
        self.selected_templates_list_view = QtWidgets.QListWidget(Generator)
        self.selected_templates_list_view.setEnabled(False)
        self.selected_templates_list_view.setMaximumSize(QtCore.QSize(16777215, 200))
        self.selected_templates_list_view.setStyleSheet("background-color: #eacabf;\n"
"border: 2px solid #d18b73;\n"
"border-radius: 5px;\n"
"color: black;\n"
"")
        self.selected_templates_list_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.selected_templates_list_view.setObjectName("selected_templates_list_view")
        self.verticalLayout_2.addWidget(self.selected_templates_list_view)
        self.show_favourites_button = QtWidgets.QPushButton(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_favourites_button.sizePolicy().hasHeightForWidth())
        self.show_favourites_button.setSizePolicy(sizePolicy)
        self.show_favourites_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.show_favourites_button.setStyleSheet("QPushButton {\n"
"    background-color: #f4c561;\n"
"    border: #395e8c 2px solid;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #f2b530;\n"
"}")
        self.show_favourites_button.setObjectName("show_favourites_button")
        self.verticalLayout_2.addWidget(self.show_favourites_button)
        self.generate_song_checkbox = QtWidgets.QCheckBox(Generator)
        self.generate_song_checkbox.setObjectName("generate_song_checkbox")
        self.verticalLayout_2.addWidget(self.generate_song_checkbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.save_results_button = QtWidgets.QPushButton(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_results_button.sizePolicy().hasHeightForWidth())
        self.save_results_button.setSizePolicy(sizePolicy)
        self.save_results_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.save_results_button.setStyleSheet("QPushButton {\n"
"    background-color: #f4c561;\n"
"    border: #395e8c 2px solid;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #f2b530;\n"
"}")
        self.save_results_button.setObjectName("save_results_button")
        self.verticalLayout_2.addWidget(self.save_results_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.generate_button = QtWidgets.QPushButton(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_button.sizePolicy().hasHeightForWidth())
        self.generate_button.setSizePolicy(sizePolicy)
        self.generate_button.setMaximumSize(QtCore.QSize(16777215, 75))
        self.generate_button.setStyleSheet("QPushButton {\n"
"    background-color: #80aabe;\n"
"    border: 2px solid #2f4557;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #6197b0;\n"
"};\n"
"\n"
"\n"
"")
        self.generate_button.setObjectName("generate_button")
        self.verticalLayout_2.addWidget(self.generate_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.templates_label = QtWidgets.QLabel(Generator)
        self.templates_label.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.templates_label.setAlignment(QtCore.Qt.AlignCenter)
        self.templates_label.setObjectName("templates_label")
        self.verticalLayout_4.addWidget(self.templates_label)
        self.templates_combo_box = QtWidgets.QComboBox(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templates_combo_box.sizePolicy().hasHeightForWidth())
        self.templates_combo_box.setSizePolicy(sizePolicy)
        self.templates_combo_box.setMinimumSize(QtCore.QSize(0, 20))
        self.templates_combo_box.setMaximumSize(QtCore.QSize(16777215, 20))
        self.templates_combo_box.setStyleSheet("QComboBox {\n"
"    border: 2px solid #e6887c;\n"
"    border-radius: 3px;\n"
"    padding: 0px 5px 0px 5px;\n"
"    background-color: #d6ccb4;\n"
"    selection-color: #51a296;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}")
        self.templates_combo_box.setObjectName("templates_combo_box")
        self.verticalLayout_4.addWidget(self.templates_combo_box)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_template_button = QtWidgets.QPushButton(Generator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_template_button.sizePolicy().hasHeightForWidth())
        self.add_template_button.setSizePolicy(sizePolicy)
        self.add_template_button.setMinimumSize(QtCore.QSize(0, 20))
        self.add_template_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.add_template_button.setStyleSheet("QPushButton {\n"
"    background-color: #52a392;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #418274;\n"
"}    \n"
"")
        self.add_template_button.setObjectName("add_template_button")
        self.horizontalLayout_4.addWidget(self.add_template_button)
        self.remove_template_button = QtWidgets.QPushButton(Generator)
        self.remove_template_button.setMinimumSize(QtCore.QSize(0, 20))
        self.remove_template_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.remove_template_button.setStyleSheet("QPushButton {\n"
"    background-color: #ba413f;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #943432;\n"
"}    \n"
"")
        self.remove_template_button.setObjectName("remove_template_button")
        self.horizontalLayout_4.addWidget(self.remove_template_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Generator)
        QtCore.QMetaObject.connectSlotsByName(Generator)

    def retranslateUi(self, Generator):
        _translate = QtCore.QCoreApplication.translate
        Generator.setWindowTitle(_translate("Generator", "Form"))
        self.text_browser.setHtml(_translate("Generator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.selected_templates_label.setText(_translate("Generator", "Selected templates:"))
        self.show_favourites_button.setText(_translate("Generator", "Show favourites"))
        self.generate_song_checkbox.setText(_translate("Generator", "Generate song"))
        self.save_results_button.setText(_translate("Generator", "SAVE RESULT"))
        self.generate_button.setText(_translate("Generator", "GENERATE"))
        self.templates_label.setText(_translate("Generator", "Templates"))
        self.add_template_button.setText(_translate("Generator", "+"))
        self.remove_template_button.setText(_translate("Generator", "-"))
